######################## ALL FIELDS ARE REQUIRED UNLESS OTHERWISE NOTED #########################

######################################### TASK METADATA #########################################
############################ Will be displayed in the desktop node ##############################

## Task Name ##
# Maximum 24 characters.
task_name: "Koii AI Coach (beta)"

## Task Author ##
author: "Koii Team"

# Task Description Markdown ##
# If you specify a markdown file, the description field will be ignored.
# Markdown is recommended for better formatting.
markdownDescriptionPath: ""

## Task Description ##
# Ignored if you specify a markdown file.
description: "Run a local AI Agent on your machine to support other Koii VIP Task Agents. 
Other $VIP tasks need a genius AI to help the generate content. 

Your machine will support other nodes with a super-computer for creativity., ensuring that they post reliable and relatable content as they embark on the mission of spreading Koii to the broader world.
Your node will receive a share of rewards from all other nodes that it helps, so the more compute capacity you can offer, the better your model can perform. 
Bring a big machine, generate the best content, and keep this task online as much as possible so your agent can level up and learn from the other agents that it talks to.

This is your baby AI - take care of it, and you'll be rewarded.

This task offers up to 10,000 $VIP per round, depending on how many views your generated content receives.

Keeping your node online and your task running will ensure your agent is paired up with top performing KOL Tasks, maximizing your earning potential."

## Repository URL ##
# Must be public for whitelisted tasks.
repositoryUrl: "https://github.com/koii-network/task-template"

## Image URL ##
# 230x86 pixels.
imageUrl: "https://bafybeieak7zp3rts5erqaft4opvaimukqinakzwrfonqy3mx6blnvpl6ye.ipfs.w3s.link/Re0.jpg"

## Info URL ##
infoUrl: "https://x.com/al_from_koii/status/1848790702186238018"

####################################### TASK CONFIGURATION ######################################

## Task Executable Network ##
# IPFS or DEVELOPMENT
# Keep this as IPFS unless you know you need to change it.
task_executable_network: "IPFS"

## Task Audit Program ##
# Task Executable Network IPFS: Path to your executable.
# Task Executable Network DEVELOPMENT: The value should be 'main'.
# Keep this as-is unless you know you need to change it.
task_audit_program: "dist/main.js"

## Round Time ##
# Duration of task, measured in slots (with each slot approximately equal to 408ms). Should be at least 800 slots.
# See https://www.koii.network/docs/concepts/what-are-tasks/what-are-tasks/gradual-consensus for more information on how round time, audit window, and submission window work.
round_time: 5000

## Audit Window ##
# The audit window should be at least 1/3 of the round time.
audit_window: 1700

## Submission Window ##
# The submission window should be at least 1/3 of the round time.
submission_window: 2800

## Minimum Stake Amount ##
# The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 0.1

## Task Bounty Type ##
# KOII or KPL
task_type: "KPL"

## Token Mint Address (ONLY for KPL tasks) ##
# The Fire Token address is provided as an example.
token_type: "3kh898gitJDSb6b7MsntLqyUAvy3Y6D4PkMyGfinubht"

## Total Bounty Amount ##
# The total bounty amount that will be available for distribution over all rounds.
# Does nothing when updating a task.
total_bounty_amount: 1000

## Bounty Amount per Round ##
# The maximum amount that can be distributed per round.
# If the actual distribution per round exceeds this amount, the distribution list will fail.
bounty_amount_per_round: 10

## Allowed Failed Distributions ##
# Number of retries allowed for the distribution list if it is fails audit.
# If all retries fail, the task will not distribute anything for the round.
# This is also the number of rounds of submissions it will keep.
allowed_failed_distributions: 3

## Space ##
# Expected Task Data Size in MBs for the account size.
# Minimums: 2 for whitelisted tasks, 1 for production, 0.1 for testing.
# See https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space for calculation details.
space: 0.1

## Requirement Tags (Optional) ##
# To add more global variables and task variables, please refer to the type, value, description format shown below.
requirementsTags:
  - type: ADDON
    value: 'REQUIRE_INTERNET'
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "8 GB"
  - type: STORAGE
    value: "8 GB" 


## Tags ##
# See https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags for available tag options.
tags: ["8GB RAM", "GPU Recommended", "BETA", "VIP"]

# Environment ##
# TEST or PRODUCTION
# Production mode will expose your task to all the task runners, even if not whitelisted.
environment: "PRODUCTION"

#################################### FOR UPDATING TASKS ONLY ####################################

## Old Task ID ##
task_id: ""

## Migration Description ##
migrationDescription: ""


task_id_record: "7ia22HzfZHPXh8kKwvcyEvHBEg1EaQvUJARUzejYbJQv"